version: 2
jobs:
  dependencies:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-v1-{{ checksum "yarn.lock" }}
            - dependencies-v1-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
            - /root/.cache/Cypress
          key: dependencies-v1-{{ checksum "yarn.lock" }}
  test:cypress:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-v1-{{ checksum "yarn.lock" }}
            - dependencies-v1-
      - run: yarn cy:cache
      - run: yarn cy:ci
      - run: yarn report:coverage
  eslint:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-v1-{{ checksum "yarn.lock" }}
            - dependencies-v1-
      - run: yarn lint:es
  build:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - build-dependencies-v1-{{ checksum "yarn.lock" }}
            - build-dependencies-v1-
            - dependencies-v1-{{ checksum "yarn.lock" }}
            - dependencies-v1-
      - run: yarn cross-env NODE_ENV=production TINIFY_API_KEY_CI=$TINIFY_API_KEY webpack
      - save_cache:
          paths:
            - node_modules
            - .cache
          key: build-dependencies-v1-{{ checksum "yarn.lock" }}
      - store_artifacts:
          path: build
          destination: build
workflows:
  version: 2
  build:
    jobs:
      - dependencies
      - test:cypress:
          requires:
            - dependencies
      - build:
          filters:
            branches:
              only: master
          requires:
            - test:cypress
            - eslint
